### ISSUE TITLE
web server stuck on saying Processing and doesnt load menu when running on apache2 with php.

### ISSUE THREAD

**Issue by Dedsec1** [RedShift1/ciscoconfig.net#4]
Hi, first off just wanted to say good job on this project, i think it has alot of potential for people as well.  i tried to setup an local copy on my Ubuntu Server with apache2 and php installed. when i tried loading up the main page it got stuck on saying Processing with the spinning gif. i know it has to be something small since the page is loading up to an point.

**Comment by RedShift1** [comment]
Check your webserver's error log (or your PHP error log if you log that separately) for any clues. Have you enabled the php_json module? The code depends on that module. Use your browser's developer mode to see what the server replies to the JSON requests.

**Comment by Dedsec1** [comment]
i did check both of my web server logs and php logs and i didnt see anything for some reason, i also used both the developer tools in chrome and firefox and i didnt see any JSON requests from the server.

**Comment by RedShift1** [comment]
If you enable the developer console, you do need to reload the page as it doesn't capture requests from before the console was open. Can you show me a screenshot of the developer console -> network?

**Comment by Dedsec1** [comment]
sure here is an screenshot 
![capture](https://cloud.githubusercontent.com/assets/8762576/18059541/6d074400-6de7-11e6-9f55-ba638cb6e9b2.PNG)

**Comment by RedShift1** [comment]
Click on the "json.php?f=getTemplates" and paste the output of the "Response" tab.

**Comment by Dedsec1** [comment]
<?php
require_once('__autoload.php');

header("Content-Type: application/json; charset=UTF-8");
// TODO: Limit class selection from $_GET

function getTemplates()
{
    return array(
        'BasicRouter' => 'Basic Cisco router, 2 interfaces',
        'TelenetCFN' => 'Router with switch EHWIC for Telenet CFN',
        'StackableSwitch' => 'Stackable layer 2 switch',
        'DMVPN' => 'DMVPN',
        'StandaloneAP' => 'Standalone access point'
    );
}

function getTemplateOptions($templateName)
{
    $ClassName = "Cisco\{$templateName}";
    $C = new $ClassName;
    return $C->GetOpts();
}

function getTemplateOptionsByGroup($templateName)
{
    $ClassName = "Cisco\{$templateName}";
    $C = new $ClassName;
    return $C->GetOptsByGroup();
}

function generate($templateName, $Opts = array())
{
    $ClassName = "Cisco\{$templateName}";
    $C = new $ClassName;
    $Options = array();
    foreach($Opts as $Entry) {
        if(preg_match("#^(._)[(._)][]$#", $Entry['name'], $Matches)) {
            $Options[$Matches[1]][$Matches[2]][] = $Entry['value'];
        } else {
            $Options[$Entry['name']] = $Entry['value'];
        }
    }

```
foreach ($C->GetOpts() as $Name => $Spec) {
    if(!isset($Options[$Name])) {
        continue;
    }

    if($Spec->getType() == 'bool') {
        if($Options[$Name] == 'true') {
            $C->setOptVal($Name, true);
        } else {
            $C->setOptVal($Name, false);
        }
    } else {
        $C->setOptVal($Name, $Options[$Name]);
    }
}
$C->Generate();
$C->sortBlocks();
return htmlentities($C->getConfig());
```

}

if(isset($_GET['template'])) {
    if(!array_key_exists($_GET['template'], getTemplates())){
        $Response['success'] = false;
        $Response['errortype'] = 'generic';
        $Response['errormsg'] = 'Invalid template';
        echo json_encode($Response);
        exit;
    }
}

switch ($_GET['f']) {
    case "getTemplates":
        $Return = getTemplates();
        break;
    case "getTemplateOptions":
        $Return = getTemplateOptions($_GET['template']);
        break;
    case "getTemplateOptionsByGroup":
        $Return = getTemplateOptionsByGroup($_GET['template']);
        break;
    case "generate":
        $Return = generate($_GET['template'], $_GET['options']);
        break;
}

$Response['success'] = true;
$Response['data'] = $Return;

echo json_encode($Response);

**Comment by RedShift1** [comment]
You don't have PHP installed or it's not activated in your Apache httpd configuration... See the documentation for your distro: https://help.ubuntu.com/community/ApacheMySQLPHP#Installing_PHP_5 Don't forget to install the PHP JSON module. Closing this ticket now, not a problem with the code...
